name: Deploy Flask App to Touge Server
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps & run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest tests/ -v

      - name: Deploy to Touge Server via SSH (Port 46380)
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.TOUGE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # 信任服务器主机密钥
          ssh-keyscan -p 46380 -H ${{ secrets.TOUGE_SERVER_IP }} >> ~/.ssh/known_hosts

          # 服务器上拉代码、装依赖、重启
          ssh -p 46380 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa root@${{ secrets.TOUGE_SERVER_IP }} << 'EOF'
            set -e
            cd /root/flask-web-app || { echo "目录不存在"; exit 1; }
            git pull origin main
            pip3 install -U pip
            pip3 install -r requirements.txt
            supervisorctl restart flask-web-app
            supervisorctl status flask-web-app
          EOF
